### ISSUE TITLE
Visitors should not visit in constructor

### ISSUE THREAD

**Issue by alexreinking** [exo-lang/exo#106]
Simply _creating_ a visitor should not start the visiting process. Instead, that should be the responsibility of `.result()`. This will make it easier to compose visitors and prevent a bunch of weird bugs that arise from calling `super().__init__()` too early (while it should _always_ be the first thing called in `__init__`).

Alternatively, with #105 we might not need visitors as badly.

**Comment by rachitnigam** [comment]
Most of the scheduling operators don't use the visitor infrastructure anymore so closing this. Also related to the broad exo-core rewrite.

**Comment by rachitnigam** [comment]
Maybe a part of #483
