### ISSUE TITLE
partition_loop() should work on loops with a variable upper bound

### ISSUE THREAD

**Issue by Hooninator** [exo-lang/exo#235]
Title. Right now, it only works on loops that have a constant upper bound such as 
`for i in par(0, 4)`

It would assist with the implementation of TRSM and TRMM if it could be changed to work on loops like
`for i in par(0, N)`

**Comment by yamaguchi1024** [comment]
To fix this, we need to be able to query the SMT solver for the assumption that makes `N - c` always positive.

**Comment by yamaguchi1024** [comment]
I think we need sth like `Check_IsPositive` in `new_eff.py` which takes proc and BinOp expression and determines if the expr is always positive or not. Tagging @gilbo
