### ISSUE TITLE
Empty structs differ in C/C++

### ISSUE THREAD

**Issue by alexreinking** [exo-lang/exo#95]
Empty structs, such as:

```
typedef struct sgemm_Context {
} sgemm_Context;
```

have different sizes in C and C++. This could lead to ABI issues down the line. If we would generate an empty struct, we should either:

1. use `void*` instead, or
2. add an `int_fast32_t dummy;` field

**Comment by gilbo** [comment]
+1 for dummy field, since the current design allows users to externally access configuration, which could be useful?
