### ISSUE TITLE
Scheduling directives with an "after" variant should have a "before" variant, too

### ISSUE THREAD

**Issue by alexreinking** [exo-lang/exo#96]
Scheduling directives with an "after" variant should have a "before" variant, too.

IIRC @yamaguchi1024 was telling me about some weird case where we need to manually write a `pass` in the starting code to schedule after it... we could also just schedule _before_ the next statement.

We should also have a pattern for inserting into the very beginning and very end of the function.

**Comment by gilbo** [comment]
Yup. Another possibility is to rethink the pointing mechanism altogether to better convey before between and after uniformly.
