### ISSUE TITLE
Pointing/Pattern Mechanism should produce traversal paths

### ISSUE THREAD

**Issue by gilbo** [exo-lang/exo#99]
Also called Zippers, Lenses.  Could call such a thing "breadcrumbs" as well.

This should probably also be thought of in connection to one-holed contexts, e.g. `C[s]` being a decomposition of a larger statement into an AST `C` containing a "hole" and `s` being another AST that plugs into the hole.

This kind of decomposition/device is central to how rewrites ought to work.

**Comment by rachitnigam** [comment]
@gilbo closing this for now because this seems like a pre-cursor to cursors. If there is more work to be done, feel free to open and add more details.
